#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  1 10:52:48 2018

@author: owner
"""

def longestCommonPrefix(strs):
    if not strs:
        return ''
    if len(strs) == 1:
        return strs[0]
    
    min_str = min(strs, key = len)
    
    idx = len(min_str) - 1
    substring = strs[0][:idx+1]
    i = 1
    while i < len(strs):
        if substring != strs[i][:idx+1]:
            idx -= 1
            substring = substring[:idx+1]
            i = 1
        else:
            i += 1
    return substring