#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  5 12:55:48 2018

@author: owner
"""
from collections import deque

def isValid(s):

    dic = {'(':')', '[':']', '{':'}'}
    q = deque()
    
    for char in s:
        if char not in q:
            q.append(char)
        else:
            if char != dic[q.pop()] or not q:
                return False
    return True if not q else False

s = {"()"}
isValid(s)